image: gitpod/workspace-full
tasks: 
  - before: npm i
    init: (cd backend ; npm i)
    command: (cd backend ; npm start)
  - command: (cd frontend ; npm i)
    command: (cd frontend ; npm start)
	


